version: '3.9'

services:
  mariadb:
    build:
      context: build
      dockerfile: Dockerfile.mariadb
    container_name: lamal-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --local-infile=1

  datasette:
    build:
      context: build
      dockerfile: Dockerfile.datasette
    depends_on:
      - mariadb
    ports:
      - "8001:8001"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["bash", "/app/convert.sh"]
